### ISSUE TITLE
Vi mangler lagnavn

### ISSUE THREAD

**Issue by jlu015** [NikolaiMagnussen/INF-2900#1]
Finn på et artig navn til laget så Nikolai ikke skriver "kake" overalt

**Comment by jlu015** [comment]
"Fancy Bear"

**Comment by NikolaiMagnussen** [comment]
Kakelaget

**Comment by s0nqr3** [comment]
Byte me

**Comment by s0nqr3** [comment]
Git rekt

**Comment by s0nqr3** [comment]
to be || ! to be

**Comment by s0nqr3** [comment]
it's not a bug, it's a feature!

**Comment by s0nqr3** [comment]
2,5 år senere, venter vi enda på at issuen skal bli resolved! 😄

**Comment by NikolaiMagnussen** [comment]
Hahahaah!!!
